on:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup R dep
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: any::knitr
            any::rmarkdown

      - name: Render and Publish Quarto homepage
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: index.qmd

      - name: Render and Publish Quarto select
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: select/index.qmd

      - name: Move CNAME to _slides folder
        run: mv CNAME _slides/CNAME || true
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _slides
